# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('comment_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=255, verbose_name='Название поста')),
                ('post_text', models.TextField(verbose_name='Текс Поста')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('post_user', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.Post'),
        ),
    ]
