# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20170207_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to='avatars/')),
                ('avatar_user', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'avatar',
            },
        ),
    ]
