# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuser', models.CharField(max_length=255)),
                ('suser', models.CharField(max_length=255)),
                ('message', models.TextField(verbose_name='Текс сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='OMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('sm_fm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.FMessage')),
            ],
        ),
    ]
